### PR TITLE
DEV: Remove old ics code

### PR DESCRIPTION
**Pull request by CvX**

### CODE REVIEW

**Review by lis2 — APPROVED** [review]

**Comment by cedk** [comment]
The ICS file was very useful to import the calendar in an external software.
Would you reconsider included it back?

**Comment by CvX** [comment]
The ics support is still there! 😃 This PR just removed the old implementation. Most of the new ics code lives in core now, see e.g. https://github.com/discourse/discourse/blob/771dddb711b97c10baf9ac5fd23d769f06f38e7e/app/assets/javascripts/discourse/app/lib/plugin-api.js#L1517-L1532

**Comment by cedk** [comment]
But for me https://discuss.tryton.org/discourse-post-event/events.ics is no more working. What is the new URL path for the new implementation?

**Comment by JulienPalard** [comment]
Same as @cedk, I don't feel the need for "one shot ICS export of one event" but I feel the need to subscribe to all events via a single endpoint, so I can subscribe to it from my calendar, like the old `events.ics`.

**Pull request merged**
