### PR TITLE
DEV: Fix acceptance test

### PR DESCRIPTION
**Pull request by jancernik**

### CODE REVIEW

**Review by CvX — APPROVED** [review]
Confirmed that core CI [does pass](https://github.com/discourse/discourse/pull/23854) with this change. Merging, thanks!

**Comment by jancernik** [comment]
Not sure what happened then, this was a random change to make a PR and test the GitHub actions. :upside_down_face:
I could never reproduce the issue

**Comment by CvX** [comment]
I'll keep an eye out on any further issues 😃

**Comment by CvX** [comment]
Well, that was quick - Dependabot PRs failed 🥲 investigating

**Comment by jancernik** [comment]
😕 The difference from the other tests is that I stripped the fixture. But I'm not sure if that has anything to do with it.

**Pull request merged**
