### PR TITLE
FEATURE: Update IN Holidays for 2023.

### PR DESCRIPTION
**Pull request by techAPJ**

### CODE REVIEW

**Review by CvX — APPROVED** [review]

**Comment by CvX** [comment]
Is the spec failure a flake or did it depend on those definitions?

**Comment by CvX** [comment]
Turns out specs fail on `main` too in 2023 😂

**Comment by techAPJ** [comment]
@CvX Looks like a flaky spec as the changes I made does not look related to the failing spec.

**Comment by techAPJ** [comment]
Closing this PR for now as we're rethinking adding holidays per region.

**Pull request closed without merging**
