### PR TITLE
Adds .ics endpoints for calendars, topics and posts

### PR DESCRIPTION
**Pull request by xfalcox**

### CODE REVIEW

**Comment by jtaylor69** [comment]
Just wondering if you had an update with regards to this PR being implemented?

**Comment by xfalcox** [comment]
> Just wondering if you had an update with regards to this PR being implemented?

Thanks for the ping @jtaylor69. I forgot about doing this :sweat_smile: 


I will try to get it merged.

**Comment by gungora** [comment]
I’m looking forward to iCal support as well 😊

**Comment by guilhem** [comment]
Gentle ping for this PR.
How can we help? :)

**Comment by 0xPetra** [comment]
Is there a way to pull funds into tasks for Discourse's OSS?

It would be a great way to fund the features we need, and get funding to build them!

What's the status of this PR? Does it need something to get merged @jjaffeux?

**Comment by decentral1se** [comment]
Dear dog, we need this. Send halp.

**Comment by rsmithlal** [comment]
Hi folks, I'd love to see this implemented.

Pavilion's Discourse Events plugin is broken at the moment after the 3.2 upgrade.

Is there anything I can do to help?

**Comment by RaitoBezarius** [comment]
@jjaffeux Could we have an official answer from maintainers of this repo on the way to go to make this PR land? I am willing to spend time fixing it, etc. But it'd be nice to understand if this repo is willing to accept such a contribution at all.

**Comment by ZogStriP** [comment]
@xfalcox is this still relevant? 🤔

**Comment by pedro-nonfree** [comment]
Let me try to summarize the situation (so I am not going to introduce new information, just put it all together closer)

@ZogStriP can you publicly clarify what happened to just close after your question that if it is still relevant?

Let me try to respond, according to the public information available:

- Is it popular? yes, this feature has 10 thumbs up and 4 hearts. **It is the most upvoted PR in this repository** [check it here](https://github.com/discourse/discourse-calendar/pulls?q=is%3Apr+sort%3Areactions-%2B1-desc+is%3Aclosed) (most upvotaed is 2). It is also the most upvoted counting all PRs on the discourse PR [check it here](https://github.com/discourse/discourse/pulls?q=is%3Apr+sort%3Areactions-%2B1-desc+is%3Aclosed) (most upvoted is 5).
- Does it introduce relevant features? Yes, @RaitoBezarius and the NixOS community are complaining that the discourse calendar, without the ics feature, [is a silo](https://github.com/NixOS/infra/issues/402). In other words, this PR solves that situation.

Given the situation, it would be nice to know what happened, because this is a relevant issue that some people would like to know what happened.

Specially, on **two questions**:

1. Is discourse going to pursue the development of this feature or a similar one?
2. Is discourse willing to accept such a contribution at all?

**Comment by ZogStriP** [comment]
> @ZogStriP can you publicly clarify what happened to just close after your question that if it is still relevant?

This was just me cleaning up old PRs.

> 1\. Is discourse going to pursue the development of this feature or a similar one?

Not as far as I'm aware no.

> 2\. Is discourse willing to accept a similar feature developed by the community?

Provided it's in a mergeable state (this one wasn't) and has tests, sure 👍

**Comment by RaitoBezarius** [comment]
> > 2. Is discourse willing to accept a similar feature developed by the community?
> 
> Provided it's in a mergeable state (this one wasn't) and has tests, sure 👍
> 
> If that's the case, do not hesitate to ping me so I can have a look 👀

Thank you for the confirmation! I will try to do my best to clean it up, add tests and ping you :).

**Pull request closed without merging**
