### PR TITLE
FIX: various TZ-related issues

### PR DESCRIPTION
**Pull request by ZogStriP**
This is a WIP to fix issues in discourse-events, notably when handling timezones, but also various UI quirks.

I'm leaving it here rather than on my HDD while I'm on holiday in case anyone wants to pick it up.

### CODE REVIEW

**Comment by cloud-construct** [comment]
Is this to fix where an event is exported to an ICS file or Google Calendar (it creates the event +1 on London time)

**Comment by ZogStriP** [comment]
> Is this to fix where an event is exported to an ICS file or Google Calendar (it creates the event +1 on London time)

I haven't tested that part. But will make sure it's fixed in the process as well 👍

**Comment by cloud-construct** [comment]
> > Is this to fix where an event is exported to an ICS file or Google Calendar (it creates the event +1 on London time)
> 
> I haven't tested that part. But will make sure it's fixed in the process as well 👍

That'd be awesome, thanks.

**Comment by davidtaylorhq** [comment]
Continued in #299

**Pull request closed without merging**
