### PR TITLE
Typo in de

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by eviltrout** [comment]
Sorry translations must be edited in transifex.

**Comment by sbernhard** [comment]
Sure. Can you please send me the link and give me access to it. I know transifex from the foreman.

**Comment by eviltrout** [comment]
I think @gschlager can help you with this, I am not super familiar with the process.

**Comment by gschlager** [comment]
This plugin isn't on Transifex and since we are switching over to Crowdin real soon, I'm not going to set it up. So, I'm merging this PR. Thanks.

**Comment by sbernhard** [comment]
btw, how should I add translations to discourse encrypt message plugin?

**Comment by gschlager** [comment]
You'd need to create a PR if you can't find it on [Transifex](https://www.transifex.com/discourse/discourse-org). But I'd prefer if you'd wait a week or two until we switch to Crowdin to make my life a little bit easier. :wink: You should be able to use the new translation platform real soon. You can subscribe to https://meta.discourse.org/t/switching-from-transifex-to-crowdin/140288 if you want to get informed when it's ready.

**Comment by sbernhard** [comment]
Thanks for letting me know.


---- Gerhard Schlager schrieb ----


You'd need to create a PR if you can't find it on Transifex<https://www.transifex.com/discourse/discourse-org>. But I'd prefer if you'd wait a week or two until we switch to Crowdin to make my life a little bit easier. 😉 You should be able to use the new translation platform real soon. You can subscribe to https://meta.discourse.org/t/switching-from-transifex-to-crowdin/140288 if you want to get informed when it's ready.

**Pull request merged**
